kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
    - containerPort: 30080  # NodePort
      hostPort: 30080
      protocol: TCP
  extraMounts:
    - hostPath: /Users/jhnam/workspace/airflow-on-k8s/dags
      containerPath: /mnt/airflow-dags
      readOnly: false
    - hostPath: /Users/jhnam/workspace/airflow-on-k8s/apps
      containerPath: /mnt/airflow-apps
      readOnly: false
- role: worker
  extraMounts:
    - hostPath: /Users/jhnam/workspace/airflow-on-k8s/dags
      containerPath: /mnt/airflow-dags
      readOnly: false
    - hostPath: /Users/jhnam/workspace/airflow-on-k8s/apps
      containerPath: /mnt/airflow-apps
      readOnly: false
- role: worker
  extraMounts:
    - hostPath: /Users/jhnam/workspace/airflow-on-k8s/dags
      containerPath: /mnt/airflow-dags
      readOnly: false
    - hostPath: /Users/jhnam/workspace/airflow-on-k8s/apps
      containerPath: /mnt/airflow-apps
      readOnly: false